# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: kuhtenia.3@osu.edu
author_name: David Kuhtenia
create_example_module: false
custom_install: custom
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: spike_aberration_detect
project_description: ''
project_license: MIT
project_name: spike-aberration-detect
project_organization: Roman-HLIS-Cosmology-PIT
python_versions:
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: none
